apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: RED-metrics
  name: RED-metrics
spec:
  endpoints:
  - interval: 10s
    port: http-port
    path: /manage/prometheus
  jobLabel: RED-metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: RED-app
