apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchen-service
  template:
    metadata:
      labels:
        app: kitchen-service
    spec:
      containers:
        - name: kitchen-service
          image: prosperagada/piza_app_tracker-service:0.1
          envFrom:
            - configMapRef:
                name: database-config
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: kitchen-service
spec:
  selector:
    app: kitchen-service
  ports:
    - port: 8081
      targetPort: 8081

