apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kitchen-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    name: kitchen-service 
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 30
  pollingInterval: 15
  triggers:
    - type: prometheus
      metadata:
        serverAddress: "http://prometheus-server.monitoring.svc.cluster.local:9090"
        query: 'rate(apache_requests_total{service="kitchen"}[2m])'
        threshold: "50"

