apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pizza-service-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      track: logs
  endpoints:
    - port: "8081"
      path: "/metrics"
