apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: pizza-route
spec:
  hostnames:
  - local.pizza.org
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /kitchen
    backendRefs:
    - name: kitchen-service
      port: 8081
  - matches:
    - path:
        type: PathPrefix
        value: /tracker
    backendRefs:
    - name: tracker-service
      port: 8082

