apiVersion: apps/v1
kind: Deployment
metadata:
  name: yugabytedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yugabytedb
  template:
    metadata:
      labels:
        app: yugabytedb
    spec:
      containers:
        - name: yugabyte
          image: yugabytedb/yugabyte:2.25.0.0-b489
          command: [ "bin/yugabyted", "start", "--background=false", "--daemon=false" ]
          ports:
            - containerPort: 5433
          volumeMounts:
            - mountPath: /var/lib/yugabytedbql/data
              name: yugabytedbdata
      volumes:
        - name: yugabytedbdata
          persistentVolumeClaim:
            claimName: yugabytedb-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: yugabytedb
  labels:
    app: yugabytedb
spec:
  ports:
    - port: 5433
  selector:
    app: yugabytedb

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: yugabytedb-volume
  labels:
    type: local
    app: yugabytedb
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/yugabytedbql

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yugabytedb-volume-claim
  labels:
    app: yugabytedb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
